apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql011                     #创建的pv名称可创建多个.
  namespace: pcl                    #属于的命名空间
spec:
  capacity:
    storage: 10Gi                        #创建的pv容量为1G
  accessModes:
    - ReadWriteOnce                       #pv的访问模式:可读可写可挂在多个节点
  persistentVolumeReclaimPolicy: Retain #回收策略
  #storageClassName: pv-nfs-mysql
  nfs:                                  #创建的pv数据来源
    path: /root/pcl/nfs/mysql/data1                     #数据源目录
    server: 172.16.44.28               #数据源ip
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql022                     #创建的pv名称可创建多个.
  namespace: pcl                    #属于的命名空间
spec:
  capacity:
    storage: 10Gi                        #创建的pv容量为1G
  accessModes:
    - ReadWriteOnce                       #pv的访问模式:可读可写可挂在多个节点
  persistentVolumeReclaimPolicy: Retain #回收策略
  #storageClassName: pv-nfs-mysql
  nfs:                                  #创建的pv数据来源
    path: /root/pcl/nfs/mysql/data2                     #数据源目录
    server: 172.16.44.28               #数据源ip
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql033                     #创建的pv名称可创建多个.
  namespace: pcl                    #属于的命名空间
spec:
  capacity:
    storage: 10Gi                        #创建的pv容量为1G
  accessModes:
    - ReadWriteOnce                       #pv的访问模式:可读可写可挂在多个节点
  persistentVolumeReclaimPolicy: Retain #回收策略
  #storageClassName: pv-nfs-mysql
  nfs:                                  #创建的pv数据来源
    path: /root/pcl/nfs/mysql/data3                    #数据源目录
    server: 172.16.44.28                #数据源ip

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql044                     #创建的pv名称可创建多个.
  namespace: pcl                    #属于的命名空间
spec:
  capacity:
    storage: 10Gi                        #创建的pv容量为1G
  accessModes:
    - ReadWriteOnce                       #pv的访问模式:可读可写可挂在多个节点
  persistentVolumeReclaimPolicy: Retain #回收策略
  #storageClassName: pv-nfs-mysql
  nfs:                                  #创建的pv数据来源
    path: /root/pcl/nfs/mysql/data4                   #数据源目录
    server: 172.16.44.28                #数据源ip