apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
spec:
  storageClassName: slow2
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/disk1/pcl/nfs/data2
    server: 172.16.12.107