apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  storageClassName: slow1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/disk1/pcl/nfs/data1
    server: 172.16.12.107